### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by justinthecoder** [salimamoukou/acv00#2]
If I try to run the code in the Python Notebook and change it into something a python script can run, the code has the error I wrote in the title when calculating the SDP using compute_sdp_clf. I believe this has something to do with the Cython file, in line 238 something has to be changed, maybe long into long long?

**Comment by salimamoukou** [comment]
Sorry for the late reply but the issue has been corrected.
