### ISSUE TITLE
TypeError: unhashable type: 'list' in compute_local_sdp function

### ISSUE THREAD

**Issue by Mythreyi-V** [salimamoukou/acv00#6]
Hello,

Thank you for a great package. I've been trying out the code on the front page. I ran into an issue when I was trying to generate the local explanatory importance scores and I wondered if you might be able to help? I got the following error:

---
```
TypeError                                 Traceback (most recent call last)
Input In [24], in <cell line: 1>()
----> 1 lximp = acv_explainer.compute_local_sdp(X_train.shape[1], sufficient_expl)

File ~/.local/lib/python3.9/site-packages/acv_explainers/acv_agnosticX.py:627, in ACXplainer.compute_local_sdp(d, sufficient_coal)
    625 flat = [item for sublist in sufficient_coal for item in sublist]
    626 flat = pd.Series(flat)
--> 627 flat = dict(flat.value_counts() / len(sufficient_coal))
    628 local_sdp = np.zeros(d)
    629 for key in flat.keys():

TypeError: unhashable type: 'list'
```

I tried to manually calculate the LEI based on your paper, since it's a just a simple percentage of how many SE in the A-SE a feature appears in, but I also found that the `sufficient_expl` list has negative values? Do they indicate a feature as well? Worth noting that sometimes the only result I get for the A-SE is -1.

**Comment by salimamoukou** [comment]
Sorry for the late reply.
In general, "-1" means that there are no features, and here it was used to initialize the lists in the code in Cython. Just ignore it. I'm going to push the latest version of ACV where they won't be there anymore.

In the meantime, note that the lximp is already calculated by the function _, _, lximp_frac = acv_explainer.sufficient_expl_rf.
Otherwise, you could use the corrected version of "acv_explainer.compute_local_sdp" (see below)

```

def compute_local_sdp(d, all_sufficient_coal):

    def compute_local_sdp_one(sufficient_coal):

        flat = [item for sublist in sufficient_coal for item in sublist]
        flat = pd.Series(flat)
        flat = dict(flat.value_counts() / len(sufficient_coal))
        local_sdp = np.zeros(d)
        for key in flat.keys():
            local_sdp[key] = flat[key]
        return local_sdp

    nb_obs = len(all_sufficient_coal)
    lximp = np.zeros(d)
    for i in range(nb_obs):
        if len(all_sufficient_coal[i]) == 0:
            nb_obs -= 1
            continue
        lximp += compute_local_sdp_one(all_sufficient_coal[i])
    return lximp / nb_ob
```
