### ISSUE TITLE
Getting `clang: error: unsupported option '-fopenmp'` when installing with pip on M1 mac

### ISSUE THREAD

**Issue by ulfaslakprecis** [salimamoukou/acv00#7]
Hi!

I'm eager to try this library out. Unfortunately I get [an error](https://github.com/salimamoukou/acv00/files/10276551/traceback.txt) upon installation:

    clang: error: unsupported option '-fopenmp'

* I updated `llvm` using homebrew (did not solve the problem).
* `clang --help | grep fopenmp` returns

        -fopenmp                Parse OpenMP pragmas and generate parallel code.

so it's just strange that this argument is not recognized during installation. 

Any idea how to solve this?

My specs are:

    Apple M1 Pro (2021)
    MacOS 12.5.1
    Python 3.10

**Comment by salimamoukou** [comment]
Hi ! 

Did you try this recommendation in the Installation section of the readme? 

OSX: ACV uses Cython extensions that need to be compiled with multi-threading support enabled. The default Apple Clang compiler does not support OpenMP. To solve this issue, obtain the lastest gcc version with Homebrew that has multi-threading enabled: see for example [pysteps installation for OSX.](https://pypi.org/project/pysteps/1.0.0/)
